### ISSUE TITLE
Unknown column 'priority' in 'order clause' 

### ISSUE THREAD

**Issue by siffring** [nystudio107/craft-retour#262]
### Describe the bug
I get this 500 error on any URL that returns a 404 after installing Retour 4.1.7 on Craft 4.3.3. 

```
Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'priority' in 'order clause' in /var/www/html/vendor/yiisoft/yii2/db/Command.php:1302
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1302): PDOStatement->execute()
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1168): yii\db\Command->internalExecute('SELECT *\nFROM `...')
#2 /var/www/html/vendor/yiisoft/yii2/db/Command.php(410): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /var/www/html/vendor/yiisoft/yii2/db/Query.php(249): yii\db\Command->queryAll()
#4 /var/www/html/vendor/craftcms/cms/src/db/Query.php(248): yii\db\Query->all(NULL)
#5 /var/www/html/vendor/nystudio107/craft-retour/src/services/Redirects.php(528): craft\db\Query->all()
#6 /var/www/html/vendor/nystudio107/craft-retour/src/services/Redirects.php(485): nystudio107\retour\services\Redirects->getRedirectsByMatchType(NULL, 1, 'regexmatch', true)
#7 /var/www/html/vendor/nystudio107/craft-retour/src/services/Redirects.php(332): nystudio107\retour\services\Redirects->getAllRegExRedirects(NULL, 1, true)
#8 /var/www/html/vendor/nystudio107/craft-retour/src/services/Redirects.php(232): nystudio107\retour\services\Redirects->findRedirectMatch('https://citco.d...', '/dldl')
#9 /var/www/html/vendor/nystudio107/craft-retour/src/Retour.php(484): nystudio107\retour\services\Redirects->handle404()
#10 [internal function]: nystudio107\retour\Retour::nystudio107\retour\{closure}(Object(craft\events\ExceptionEvent))
#11 /var/www/html/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(craft\events\ExceptionEvent))
#12 /var/www/html/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger('craft\\web\\Error...', 'beforeHandleExc...', Object(craft\events\ExceptionEvent))
#13 /var/www/html/vendor/craftcms/cms/src/web/ErrorHandler.php(49): yii\base\Component->trigger('beforeHandleExc...', Object(craft\events\ExceptionEvent))
#14 [internal function]: craft\web\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#15 {main}
```

### To reproduce
Steps to reproduce the behaviour:
1. Install Retour 4.1.7 
`ddev craft plugin/install retour`
2. Go to any URL that returns a 404 error
3. See error message above

### Expected behaviour
See a 404 error and have it logged in Retour.

### Screenshots

Here are the migrations that run on install.

![CleanShot 2022-12-06 at 19 38 40@2x](https://user-images.githubusercontent.com/70836/206066768-3485bbfd-b175-4ab7-9335-0fc795d7d381.png)

### Versions
- Plugin version: 4.1.7
- Craft version: 4.3.3

**Comment by accarpenter** [comment]
Same issue.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-retour/commit/ae42ff4bcee1f0b4cdf37f6c7910659c0ea57f83 & https://github.com/nystudio107/craft-retour/commit/afc35c4575820da2f0b9c24024acaa7aa30ff537

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop as 3.2.6”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop-v4 as 4.1.8”,
```
Then do a `composer clear-cache && composer update`

**Comment by khalwat** [comment]
Released:

Craft 3: Version 3.2.6 -> https://github.com/nystudio107/craft-retour/releases/tag/3.2.6

Craft 4: Version 4.1.8 -> https://github.com/nystudio107/craft-retour/releases/tag/4.1.8

Unfortunately you'll need to uninstall and re-install the plugin

**Comment by thomEpps** [comment]
Still getting this today using Retour v4.1.8 on Craft v4.3.4. 
Have uninstalled & removed the old plugin version & started from scratch with the same results

**Comment by khalwat** [comment]
@thomEpps possibly the install migration is still in the database? I will verify today

**Comment by thomEpps** [comment]
thanks @khalwat

**Comment by khalwat** [comment]
@thomEpps confirmed, and I see what the issue is. Apologies, I will have a fix out shortly.

**Comment by khalwat** [comment]
Released a fix:

Craft 3: Version 3.2.7 -> https://github.com/nystudio107/craft-retour/releases/tag/3.2.7

Craft 4: Version 4.1.9 -> https://github.com/nystudio107/craft-retour/releases/tag/4.1.9

**Comment by thomEpps** [comment]
cheers @khalwat thats fixed it for me 👍

**Comment by shifuma** [comment]
I'm still getting this on 4.1.10. I tried to add a redirect and got the error 'Couldn't save redirect settings because it'd create a redirect loop.' Now going to that URL (which wasn't redirected) gives the error.

Edit: Uninstall and Reinstall has fixed it; there was some old data in the database from when I had tried the plugin previously, maybe connected to that.

**Comment by khalwat** [comment]
Sounds like a migration wasn't run, perhaps @shifuma ?
