### ISSUE TITLE
PostgreSQL compatibility issues

### ISSUE THREAD

**Issue by brandonkelly** [nystudio107/craft-retour#30]
Noticing some MySQL-specific SQL syntax in a couple places:

https://github.com/nystudio107/craft-retour/blob/40c84cfbdaeb10866c3655f805bb96f5d8d1ef41/src/controllers/ChartsController.php#L128-L136

`CURDATE()` isn’t supported by PostgreSQL, and `hitLastTime` and `handledByRetour` will be normalized to lowercase unless you wrap them in `[[` and `]]`s.

https://github.com/nystudio107/craft-retour/blob/40c84cfbdaeb10866c3655f805bb96f5d8d1ef41/src/services/Statistics.php#L82-L87

`CURDATE()` and lowercase column name again. On line 85 instead of adding the brackets you could switch to

```php
->andWhere(['handledByRetour' => $handledInt])
```

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-retour/commit/b269e9be4c26390105b447cf1dcab504a0137f1a & https://github.com/nystudio107/craft-retour/commit/2d5f5827d21776a6ebf25f7afe509731ed21267a

Interestingly, `getRecentStatistics()` is vestigial, a holdover from the Craft 2.x version.

**Comment by brandonkelly** [comment]
It must still get called somehow because I ran across this bug when trying to view the share URL for an in-progress blog post.

**Comment by khalwat** [comment]
Weird... in any event, it should be fixed! lmk if that's not the case, but it's working on my Postgres test case
